### ISSUE TITLE
Make unique URL a simple base64 encode

### ISSUE THREAD

**Issue by jaicab** [davidguerreiro/evscalculator#16]
To speed up, avoid unnecessary stuff on the DB and more importantly, avoid collision, we should create the unique URL from the data we have for each training. So we won't need the `id_url` field any longer as we can decode it back into the unique row's ID. We should also add some unique strings at the beginning and the end to make it more random.

For example, users with ID '1' and '456' would have this URL strings:

``` php
base64encode('calcu1evs'); // Y2FsY3UxZXZz
base64encode('calcu456evs'); // Y2FsY3U0NTZldnM=
```

The best thing about this is that we than can decode this URL to get the ID:

``` php
base64decode('Y2FsY3UxZXZz'); // calcu1evs
base64decode('Y2FsY3U0NTZldnM='); // calcu456evs
```

We can then make a regular expression to grab the number between 'calcu' and 'evs'. And we got the ID!  
:+1:

**Comment by davidguerreiro** [comment]
Nice idea, completely agree

**Comment by jaicab** [comment]
This is now done with the Hashids library.
