### ISSUE TITLE
Change link on repo

### ISSUE THREAD

**Issue by jaicab** [davidguerreiro/evscalculator#17]
Since we'll be using SSL throughout the app, we need to change the URL in the repo (beside the description) from http to https.

**Comment by davidguerreiro** [comment]
Did you already change it ?

**Comment by jaicab** [comment]
No, I can't change it because i'm not the repo author. It's the one on https://github.com/davidguerreiro/evscalculator, right after the description. It needs to be https not http. Then you can close the issue.

**Comment by jaicab** [comment]
Can you please do this one @davidguerreiro? I can't because I'm not the repo owner and it's an easy one.
