### ISSUE TITLE
Conventions

### ISSUE THREAD

**Issue by jaicab** [davidguerreiro/evscalculator#2]
We should have some conventions to work independently. Here are some common conventions we should use:
- **api** folder to put PHP files that correspond to the AJAX requests. This would be the root for api.evscalculator.com
- **scss** folder will contain all the Sass files, which will combine in a single style.css file. There should never be more than one CSS file requested per HTML documents (unless it's a fallback for a form).
- **js** folder for all JavaScript files.
- **lib** for all PHP files that are used on the templates (never the ones used on the API, these should be theme-specific should be separate).
- **pokemon_img** for all pokemon images, where _pokemon_img_ would be the root for img.evscalculator.com. This way the image system would have the ability to grow if we need to use different images for every pokemon.
  - **pokemon_img/small** Will contain the small version of the images.
  - **pokemon_img/medium** Will contain the normal version of the images.

Write your opinions down below.

**Comment by davidguerreiro** [comment]
Fantastic ! I completely agree with you.

Actually, we already have two images for every pokemon, the small one and the gif.

**Comment by jaicab** [comment]
Do you think it's worth worrying about the images for version 1.0? Maybe we should completely ignore them for now, don't know.

**Comment by davidguerreiro** [comment]
Sure, we only need the small version for hordes and items (Vitamins, berries, etc)

**Comment by jaicab** [comment]
We can move this into the docs.
