### ISSUE TITLE
User journey

### ISSUE THREAD

**Issue by jaicab** [davidguerreiro/evscalculator#5]
Here are some of the sketches for the user journey.

Homepage
![image](https://cloud.githubusercontent.com/assets/1174434/11023819/ec7c7fde-867a-11e5-9a90-ce672a01b458.png)
Training page
<img width="640" alt="evscalculator - 2" src="https://cloud.githubusercontent.com/assets/1174434/11023821/f4336972-867a-11e5-9feb-e85678600dc2.png">
Formulas
<img width="1024" alt="evscalculator - 4" src="https://cloud.githubusercontent.com/assets/1174434/11023822/f6079c32-867a-11e5-9ba5-8a720e2f0bbd.png">
Training modes
<img width="1024" alt="evscalculator - 3" src="https://cloud.githubusercontent.com/assets/1174434/11023824/fe9f3cf6-867a-11e5-8f01-e43fa5fa975c.png">

**Comment by davidguerreiro** [comment]
I have noticed that the formula is wrong. It's not 18, it's 10. X is equal to 1. If you resolve the equation...
(Yes, I know, it was my fault anyway... )
