### ISSUE TITLE
GitHub chat

### ISSUE THREAD

**Issue by jaicab** [davidguerreiro/evscalculator#8]
We should have a chat, Álvaro you (@davidguerreiro) and me about GitHub, issues, PRs and labels. We need to start using labels on issues for example, as they're getting big.

**Markdown**
- Explanation: http://www.remarq.io/articles/five-minutes-to-markdown-mastery/
- Practice: http://markdowntutorial.com/

**GitHub**
- How to use GitHub's website and basic conceptos: https://guides.github.com/activities/hello-world/
- Process (flow): https://guides.github.com/introduction/flow/
- Issues: https://guides.github.com/features/issues/
- Where to use Markdown on GitHub: https://guides.github.com/features/mastering-markdown/
- How to use GitHub for Windows app: https://www.youtube.com/watch?v=u12zHGRfiKU

**Comment by davidguerreiro** [comment]
Good !! What about tomorrow ?

**Comment by jaicab** [comment]
I'll be pretty busy tomorrow, but start with the introductions I've put at the top.

**Comment by jaicab** [comment]
We've had this chat, I'll merge this information into the docs in case we need it.
